import React, { useEffect, useState } from 'react';
import { FiSearch, FiFilter, FiDownload, FiEye, FiFile, FiUser, FiCalendar, FiFileText } from 'react-icons/fi';
import { advancedDocumentService } from '../services/advancedService';
import toast from 'react-hot-toast';

const GeneratedDocuments: React.FC = () => {
  const [docs, setDocs] = useState([]);
  const [showFilter, setShowFilter] = useState(false);
  const [loading, setLoading] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [filters, setFilters] = useState({
    template: '',
    generatedBy: '',
    startDate: '',
    endDate: ''
  });

  useEffect(() => {
    loadDocuments();
  }, []);

  const loadDocuments = async () => {
    setLoading(true);
    try {
      const response = await advancedDocumentService.getGeneratedDocuments();
      setDocs(response.data);
    } catch (error) {
      toast.error('Failed to load generated documents');
    } finally {
      setLoading(false);
    }
  };

  const handleFilterChange = (key: string, value: string) => {
    setFilters(prev => ({ ...prev, [key]: value }));
  };

  const applyFilters = () => {
    loadDocuments();
  };

  const clearFilters = () => {
    setFilters({
      template: '',
      generatedBy: '',
      startDate: '',
      endDate: ''
    });
    setSearchTerm('');
  };

  const downloadDocument = async (id: number) => {
    try {
      await advancedDocumentService.downloadGeneratedDocument(id);
      toast.success('Download started');
    } catch (error) {
      toast.error('Download failed');
    }
  };

  const filteredDocuments = () => {
    return docs.filter((doc: any) => 
      doc.template?.name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      doc.generated_by?.email?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      doc.generated_at?.toLowerCase().includes(searchTerm.toLowerCase())
    );
  };

  const getDocumentTypeColor = (type: string) => {
    const colors: { [key: string]: string } = {
      'invoice': 'bg-blue-100 text-blue-800',
      'receipt': 'bg-green-100 text-green-800',
      'letter': 'bg-purple-100 text-purple-800',
      'contract': 'bg-orange-100 text-orange-800',
      'report': 'bg-gray-100 text-gray-800',
    };
    return colors[type?.toLowerCase()] || 'bg-gray-100 text-gray-800';
  };

  const getStats = () => {
    const stats = {
      total: docs.length,
      today: docs.filter((doc: any) => {
        const today = new Date().toDateString();
        return new Date(doc.generated_at).toDateString() === today;
      }).length,
      thisWeek: docs.filter((doc: any) => {
        const weekAgo = new Date();
        weekAgo.setDate(weekAgo.getDate() - 7);
        return new Date(doc.generated_at) >= weekAgo;
      }).length,
      thisMonth: docs.filter((doc: any) => {
        const monthAgo = new Date();
        monthAgo.setMonth(monthAgo.getMonth() - 1);
        return new Date(doc.generated_at) >= monthAgo;
      }).length,
    };
    return stats;
  };

  const stats = getStats();

  return (
    <div className="bg-white rounded-xl shadow p-8 min-h-[60vh]">
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-2xl font-bold text-purple-700">Generated Documents</h2>
        <div className="flex gap-2">
          <button 
            onClick={() => setShowFilter(!showFilter)}
            className="flex items-center gap-2 px-4 py-2 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition"
          >
            <FiFilter />
            Filter
          </button>
        </div>
      </div>

      {/* Search Bar */}
      <div className="mb-6 relative">
        <FiSearch className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
        <input
          type="text"
          placeholder="Search documents..."
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
          className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
        />
      </div>

      {/* Filter Panel */}
      {showFilter && (
        <div className="mb-6 p-4 bg-gray-50 rounded-lg">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <input
              type="text"
              placeholder="Template Name"
              value={filters.template}
              onChange={(e) => handleFilterChange('template', e.target.value)}
              className="px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
            />
            <input
              type="text"
              placeholder="Generated By"
              value={filters.generatedBy}
              onChange={(e) => handleFilterChange('generatedBy', e.target.value)}
              className="px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
            />
            <input
              type="date"
              placeholder="Start Date"
              value={filters.startDate}
              onChange={(e) => handleFilterChange('startDate', e.target.value)}
              className="px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
            />
            <div className="flex gap-2">
              <button
                onClick={applyFilters}
                className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition"
              >
                Apply
              </button>
              <button
                onClick={clearFilters}
                className="px-4 py-2 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 transition"
              >
                Clear
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
        <div className="bg-purple-50 p-4 rounded-lg">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-purple-600">Total Documents</p>
              <p className="text-2xl font-bold text-purple-700">{stats.total}</p>
            </div>
            <FiFile className="text-purple-600 text-2xl" />
          </div>
        </div>
        <div className="bg-green-50 p-4 rounded-lg">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-green-600">Today</p>
              <p className="text-2xl font-bold text-green-700">{stats.today}</p>
            </div>
            <FiFile className="text-green-600 text-2xl" />
          </div>
        </div>
        <div className="bg-blue-50 p-4 rounded-lg">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-blue-600">This Week</p>
              <p className="text-2xl font-bold text-blue-700">{stats.thisWeek}</p>
            </div>
            <FiFile className="text-blue-600 text-2xl" />
          </div>
        </div>
        <div className="bg-orange-50 p-4 rounded-lg">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-orange-600">This Month</p>
              <p className="text-2xl font-bold text-orange-700">{stats.thisMonth}</p>
            </div>
            <FiFile className="text-orange-600 text-2xl" />
          </div>
        </div>
      </div>

      {/* Documents Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {filteredDocuments().map((doc: any) => (
          <div key={doc.id} className="bg-white border border-gray-200 rounded-lg shadow-sm hover:shadow-md transition-shadow">
            <div className="p-6">
              <div className="flex items-start justify-between mb-4">
                <div className="flex-1">
                  <h3 className="text-lg font-semibold text-gray-900 mb-2">
                    {doc.template?.name || 'Untitled Document'}
                  </h3>
                  <div className="space-y-2 text-sm text-gray-600 mb-3">
                    <div className="flex items-center gap-2">
                      <FiUser className="text-gray-400" />
                      <span>{doc.generated_by?.email || 'Unknown User'}</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <FiCalendar className="text-gray-400" />
                      <span>{new Date(doc.generated_at).toLocaleString()}</span>
                    </div>
                  </div>
                  <div className="flex items-center gap-2 mb-3">
                    <span className={`px-2 py-1 rounded-full text-xs font-medium ${getDocumentTypeColor(doc.template?.document_type)}`}>
                      {doc.template?.document_type || 'Unknown'}
                    </span>
                    <span className="px-2 py-1 bg-green-100 text-green-800 rounded-full text-xs font-medium">
                      Generated
                    </span>
                  </div>
                  {doc.file_path && (
                    <p className="text-sm text-gray-500">
                      File: {doc.file_path.split('/').pop()}
                    </p>
                  )}
                </div>
              </div>
              
              <div className="flex items-center justify-between pt-4 border-t border-gray-100">
                <div className="text-xs text-gray-500">
                  ID: #{doc.id}
                </div>
                <div className="flex gap-2">
                  <button 
                    className="p-2 text-blue-600 hover:text-blue-800 hover:bg-blue-50 rounded-lg transition"
                    title="Preview"
                  >
                    <FiEye size={16} />
                  </button>
                  <button 
                    onClick={() => downloadDocument(doc.id)}
                    className="p-2 text-green-600 hover:text-green-800 hover:bg-green-50 rounded-lg transition"
                    title="Download"
                  >
                    <FiDownload size={16} />
                  </button>
                  <button 
                    className="p-2 text-purple-600 hover:text-purple-800 hover:bg-purple-50 rounded-lg transition"
                    title="View Template"
                  >
                    <FiFileText size={16} />
                  </button>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Empty State */}
      {filteredDocuments().length === 0 && !loading && (
        <div className="text-center py-12">
          <FiFile className="mx-auto h-12 w-12 text-gray-400" />
          <h3 className="mt-2 text-sm font-medium text-gray-900">No generated documents found</h3>
          <p className="mt-1 text-sm text-gray-500">
            {searchTerm || Object.values(filters).some(f => f) 
              ? 'Try adjusting your search or filter criteria.' 
              : 'No documents have been generated yet.'}
          </p>
        </div>
      )}

      {/* Loading State */}
      {loading && (
        <div className="text-center py-12">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-purple-900 mx-auto"></div>
          <p className="mt-2 text-sm text-gray-500">Loading generated documents...</p>
        </div>
      )}
    </div>
  );
};

export default GeneratedDocuments; 